[package]
name = "snapshot-editor"
version = "1.13.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "snapshot-editor"
bench = false

[dependencies]
clap = { version = "4.5.38", features = ["derive", "string"] }
displaydoc = "0.2.5"

fc_utils = { package = "utils", path = "../utils" }
libc = "0.2.172"
log-instrument = { path = "../log-instrument", optional = true }
semver = "1.0.26"
thiserror = "2.0.12"
vmm = { path = "../vmm" }
vmm-sys-util = "0.12.1"

[target.'cfg(target_arch = "aarch64")'.dependencies]
clap-num = "1.2.0"

[features]
tracing = ["log-instrument", "fc_utils/tracing", "vmm/tracing"]

[lints]
workspace = true
