[package]
name = "snapshot-editor"
version = "1.5.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "snapshot-editor"
bench = false

[dependencies]
clap = { version = "4.4.6", features = ["derive", "string"] }
displaydoc = "0.2.4"
libc = "0.2.148"
snapshot = { path = "../snapshot" }
thiserror = "1.0.49"
vmm = { path = "../vmm" }

fc_utils = { package = "utils", path = "../utils" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
clap-num = "1.0.2"
