[package]
name = "snapshot-editor"
version = "1.7.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "snapshot-editor"
bench = false

[dependencies]
clap = { version = "4.5.1", features = ["derive", "string"] }
displaydoc = "0.2.4"
libc = "0.2.153"
log-instrument = { path = "../log-instrument", optional = true }
semver = "1.0.22"
thiserror = "1.0.57"
vmm = { path = "../vmm" }

fc_utils = { package = "utils", path = "../utils" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
clap-num = "1.0.2"

[features]
tracing = ["log-instrument", "fc_utils/tracing", "vmm/tracing"]
