[package]
name = "mmds"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
lazy_static = ">=1.1.0"
serde_json = ">=1.0.9"

micro_http = { path = "../micro_http" }
