version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    allow:
      - dependency-type: "all"
    groups:
      rust-vmm:
        patterns:
          - "vmm-sys-util"
          - "kvm-bindings"
          - "kvm-ioctls"
          - "vm-memory"
          - "vhost"
          - "linux-loader"
          - "vm-allocator"
          - "event-manager"
          - "vm-superio"
      firecracker:
        patterns:
          - "*"
        exclude-patterns:
          - "vmm-sys-util"
          - "kvm-bindings"
          - "kvm-ioctls"
          - "vm-memory"
          - "vhost"
          - "linux-loader"
          - "vm-allocator"
          - "event-manager"
          - "vm-superio"
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

