[package]
name = "firecracker"
version = "0.18.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
backtrace = {version = "0.3", features = ["libunwind", "libbacktrace", "std"], default-features = false}
clap = { version = ">=2.27.1", default-features = false}

api_server = { path = "api_server" }
fc_util = { path = "fc_util" }
jailer = { path = "jailer" }
logger = { path = "logger" }
mmds = { path = "mmds" }
seccomp = { path = "seccomp" }
vmm = { path = "vmm" }

[dev-dependencies]
tempfile = ">=3.0.2"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"

[workspace]
