[tool.poetry]
name = "tool.poetry"
version = "0.1.0"
description = "Firecracker python dependencies"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
aws-embedded-metrics = "*"
black = "*"
boto3 = "*"
botocore = "*"
dataclasses = "*"
# We need to fix the gitlint version since version 0.17.0 has a problem:
# https://pythonissues.com/issues/1410824
gitlint = "0.16.0"
nsenter = "*"
openapi-spec-validator = "*"
pandas = "*"
psutil = "5.7.0"
pylint = "*"
pytest = "*"
pytest-json-report = "*"
pytest-timeout = "*"
pytest-xdist = "*"
python = "3.10.4"
PyYAML = "*"
requests = "*"
requests-unixsocket = "*"
retry = "*"
setproctitle = "*"
typing-extensions = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
