[tool.poetry]
name = "tool.poetry"
version = "0.1.0"
description = "Firecracker python dependencies"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
aws-embedded-metrics = "^3.1.0"
black = "^23.3.0"
boto3 = "^1.26.140"
botocore = "^1.29.140"
gitlint = "^0.19.1"
isort = "^5.12.0"
nsenter = "^0.2"
openapi-spec-validator = "^0.5.6"
pandas = "^2.0.1"
psutil = "^5.9.5"
pylint = "^2.17.4"
pytest = "^7.3.1"
pytest-json-report = "^1.5.0"
pytest-rerunfailures = "^11.1.2"
pytest-timeout = "^2.1.0"
pytest-xdist = "^3.3.1"
python = "3.10.*"
PyYAML = "^6.0"
requests = "^2.31.0"
requests-unixsocket = "^0.3.0"
retry = "^0.9.2"
setproctitle = "^1.3.2"
tenacity = "^8.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
