[tool.poetry]
name = "tool.poetry"
version = "0.1.0"
description = "Firecracker python dependencies"
authors = ["Your Name <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
aws-embedded-metrics = "^3.1.0"
black = "^24.3.0"
# Gitlint locks this to 8.1.3. Lock from our side too to prevent different versions
click = "8.1.3"
filelock = "^3.13.4"
gitlint = "^0.19.1"
ipython = "^8.15.0"
isort = "^5.12.0"
mdformat = "^0.7.17"
mdformat-gfm = "^0.3.5"
mdformat-footnote = "^0.1.1"
mdformat-frontmatter = "^2.0.8"
openapi-spec-validator = "^0.7.1"
psutil = "^6.0.0"
pylint = "^3"
pytest = "^8"
pytest-json-report = "^1.5.0"
pytest-rerunfailures = "^14"
pytest-timeout = "^2.3.1"
pytest-xdist = "^3.5"
python = "^3.10.0"
PyYAML = "^6.0"
requests = "^2.32.2"
requests-unixsocket2 = "^0.4.0"
scipy = "^1.11.2"
setproctitle = "^1.3.2"
tenacity = "^8.2.2"


[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
