[package]
name = "mmds"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
lazy_static = ">=1.1.0"
serde_json = ">=1.0.9"
versionize = ">=0.1.2"
versionize_derive = ">=0.1.1"

dumbo = { path = "../dumbo" }
logger = { path = "../logger" }
micro_http = { path = "../micro_http" }
utils = { path = "../utils" }
snapshot = { path = "../snapshot" }

