[package]
name = "mmds"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
aes-gcm =  { version = "0.10.1", default-features = false, features = ["aes"] }
base64 = "0.13.0"
bincode = "1.2.1"
derive_more = { version = "0.99.17", default-features = false, features = ["from"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
thiserror = "1.0.32"
versionize = "0.1.10"
versionize_derive = "0.1.5"

dumbo = { path = "../dumbo" }
logger = { path = "../logger" }
micro_http = { git = "https://github.com/firecracker-microvm/micro-http" }
snapshot = { path = "../snapshot" }
utils = { path = "../utils" }
