[package]
name = "mmds"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
aes-gcm = "0.10.1"
base64 = "0.13.0"
bincode = "1.2.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
versionize = "0.1.6"
versionize_derive = "0.1.4"
derive_more = { version = "0.99.17", default-features = false, features = ["from"] }

dumbo = { path = "../dumbo" }
logger = { path = "../logger" }
micro_http = { git = "https://github.com/firecracker-microvm/micro-http", rev = "4b18a04" }
snapshot = { path = "../snapshot" }
utils = { path = "../utils" }
