[package]
name = "snapshot"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
autobenches = false
license = "Apache-2.0"

[dependencies]
libc = "0.2.117"
versionize = "0.2.0"
versionize_derive = "0.1.5"
thiserror = "1.0.32"

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }

[[bench]]
name = "version_map"
harness = false
