[package]
name = "rate_limiter"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
libc = ">=0.2.39"
timerfd = ">=1.0"

logger = { path = "../logger" }
utils = { path = "../utils" }
snapshot = { path = "../snapshot" }
versionize = { path = "../versionize" }
versionize_derive = { path = "../versionize_derive" }
