[package]
name = "rate_limiter"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
libc = ">=0.2.39"
timerfd = ">=1.0"
versionize = ">=0.1.6"
versionize_derive = ">=0.1.3"

logger = { path = "../logger" }
utils = { path = "../utils" }
snapshot = { path = "../snapshot" }

