[build]
target-dir = "build/cargo_target"
rustflags = [
  "-Ccodegen-units=1",
]

[net]
git-fetch-with-cli = true

[env]
AWS_LC_SYS_NO_JITTER_ENTROPY = "1"
# disable AVX512 as it adds 600k of binary size
# this was only used for MMDS token generation
AWS_LC_SYS_CFLAGS = "-DMY_ASSEMBLER_IS_TOO_OLD_FOR_512AVX"
