[package]
name = "rebase-snap"
version = "1.15.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "rebase-snap"
bench = false

[features]
tracing = ["log-instrument", "utils/tracing"]

[dependencies]
displaydoc = "0.2.5"
libc = "0.2.177"
log-instrument = { path = "../log-instrument", optional = true }
thiserror = "2.0.17"
vmm-sys-util = "0.15.0"

utils = { path = "../utils" }

[lints]
workspace = true
