[package]
name = "rebase-snap"
version = "1.7.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "rebase-snap"
bench = false

[dependencies]
displaydoc = "0.2.4"
libc = "0.2.153"
log-instrument = { path = "../log-instrument", optional = true }
thiserror = "1.0.57"

utils = { path = "../utils" }

[features]
tracing = ["log-instrument", "utils/tracing"]
