[package]
name = "rebase-snap"
version = "1.5.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "rebase-snap"
bench = false

[dependencies]
displaydoc = "0.2.4"
libc = "0.2.148"
thiserror = "1.0.48"

utils = { path = "../utils" }
