[package]
name = "rebase-snap"
version = "1.10.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "rebase-snap"
bench = false

[dependencies]
displaydoc = "0.2.5"
libc = "0.2.159"
log-instrument = { path = "../log-instrument", optional = true }
thiserror = "1.0.64"
vmm-sys-util = "0.12.1"

utils = { path = "../utils" }

[features]
tracing = ["log-instrument", "utils/tracing"]

[lints]
workspace = true
