[package]
name = "jailer"
version = "0.23.2"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"
build = "../../build.rs"

[dependencies]
libc = ">=0.2.39"
regex = ">=1.0.0"

utils = { path = "../utils" }
