[package]
name = "jailer"
version = "1.5.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
build = "../../build.rs"
description = "Process for starting Firecracker in production scenarios; applies a cgroup/namespace isolation barrier and then drops privileges."
homepage = "https://firecracker-microvm.github.io/"
license = "Apache-2.0"

[dependencies]
libc = "0.2.117"
nix = { version = "0.26.2", default-features = false, features = ["dir"] }
regex = { version = "1.8.3", default-features = false, features = ["std"] }
thiserror = "1.0.32"
tracing = { version = "0.1.37", features = ["attributes"] }

utils = { path = "../utils" }
