[package]
name = "jailer"
version = "1.10.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
description = "Process for starting Firecracker in production scenarios; applies a cgroup/namespace isolation barrier and then drops privileges."
homepage = "https://firecracker-microvm.github.io/"
license = "Apache-2.0"

[[bin]]
name = "jailer"
bench = false

[dependencies]
libc = "0.2.159"
log-instrument = { path = "../log-instrument", optional = true }
nix = { version = "0.29.0", default-features = false, features = ["dir"] }
regex = { version = "1.11.0", default-features = false, features = ["std"] }
thiserror = "1.0.64"
vmm-sys-util = "0.12.1"

utils = { path = "../utils" }

[features]
tracing = ["log-instrument", "utils/tracing"]

[lints]
workspace = true
