[package]
name = "log-instrument-macros"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
description = "Offers an attribute procedural macro that adds `log::trace!` events at the start and end of attributed functions."
license = "Apache-2.0"

[lib]
proc-macro = true
bench = false

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.72", features = ["full", "extra-traits"] }

[lints]
workspace = true
